modLoader="javafml"
loaderVersion="[41,)"
license="All Rights Reserved unless otherwise explicitly stated"

[[mods]]
modId="nuke"
version="1.0"
displayName="Nuke"
displayURL="https://www.curseforge.com/minecraft/mc-mods/nuke-forge"
logoFile="logo.png"
authors="MrScautHD"
description='''This Mod add a Nuke to the Game'''

[[dependencies.nuke]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19]"
    ordering="NONE"
    side="BOTH"

[[dependencies.nuke]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.98,]"
    ordering="NONE"
    side="BOTH"